### ISSUE TITLE
Suggestion: option to block all http requests and option to block all http requests on https pages

### ISSUE THREAD

**Issue by Halibut80** [futpib/policeman#113]

**Comment by heforfree** [comment]
@futpib also look this #61

**Comment by futpib** [comment]
Is this what "https sandbox" ruleset does? Check [reject_http](https://github.com/futpib/policeman-rulesets/blob/master/general/reject_http.ruleset) for the other part of your request.

**Comment by heforfree** [comment]
in pre9 if i put reject_http on top of ruleset
![image 1](https://cloud.githubusercontent.com/assets/2247864/5789246/f7e1c9c4-9e77-11e4-8fb1-88f7e1c5df8f.png)
![image 2](https://cloud.githubusercontent.com/assets/2247864/5789247/fc870e6c-9e77-11e4-9a0b-19dd2f1021c9.png)

but pre10 it allow http request
HTTP Nowhere Version 2.0.2 do somthing like pre9
but problem with pre9 is if put reject_http on top and then make some temp or persistent rule
it wont work because first match wins

**Comment by futpib** [comment]
@heforfree I don't get it. Do you think that **navigation** to http pages has to be prevented?

**Comment by heforfree** [comment]
@futpib 
when enable reject_http ruleset then yes it must block go to site
then with this rulset user can create 100% trusted domain.with this way user can control
every request that firefox make or addon make request
example firefox make request to ocsp.digicert.com and many other request
policeman can not block this request
anyway i see it make too Complex so if you want close this

**Comment by CrisBRM** [comment]
I'm confused. Does policeman lack the ability to force strict HTTPS on demand (no mixed content)?

**Comment by futpib** [comment]
@CrisBRM Policeman can block http content on https pages by means of "https sandbox" ruleset. In fact Firefox is also able to do that out-of-box (see #134).
