### ISSUE TITLE
Redirection blocking

### ISSUE THREAD

**Issue by kirill9000** [futpib/policeman#115]
Hello.
I'd like to thank you for your outstanding work. I switched from RequestPolicy to Policeman for it's feature-richness and much much more convenient interface. You have my deepest appreciation.

But I miss one feature from RequestPolicy - blocking of redirections from (and to) non-whitelisted domains. When user clicks link that attempts to redirect him, RP displays destination URL and asks user whether he wishes to follow. It's very useful against various link shortening services.

May I suggest that such feature should be incorporated into Policeman?

**Comment by bastik-tor** [comment]
Indeed a very useful feature. It displayed an infobar on the top of the page, asking what to do.

Depending on how it is going to be implemented you may want to optionally allow http to https redirects for the same domain, despite the blocking state of the source. (e.g. http://www.example.org/ can redirect to https://www.example.org/ without Policeman interfering with it.)

Since RequestPolicy was able to either allow or reject any request, it was easy to tell what a non-white-listed domain actually is. With Policeman I can allow requests for images from ```github.com``` to ```imagehoster.net```, but still not want to be redirected to it. Either this would mean redirects appear with their own category in the popup or that redirects are treated in a different way.

**Comment by futpib** [comment]
522dd1c26ea46235a491ca58c3c2a5bee203d744 and some older commits address this issue

**Comment by Halibut80** [comment]
@futpib Redirects blocking not work for me:
<a href="https://lh3.ggpht.com/-YGaX0h5bXR4/VM7cFP7YRwI/AAAAAAAAamI/bJQj2vkL0Kk/s0/red.gif">gif</a>
From accounts.google.com to mail.google.com.

**Comment by futpib** [comment]
@Halibut80 What's your *about:policeman#rulesets-manager* setup?

**Comment by Halibut80** [comment]
@futpib Oh, sorry, my fault.. I have enabled "allow same second level domain" ruleset.

**Comment by heforfree** [comment]
just change that icon to policeman  redirect icon
![image1](https://cloud.githubusercontent.com/assets/2247864/6000756/20d253e0-aaf7-11e4-8b2c-6d23b0cc2957.png)

also example i am on http://example.com/ then in searchbar i type something
and then press enter then notification ask me allow redirect from www.example.com to www.google.com
i can create rule page anydomain to google.com
but just it happen in clean profile?
and not happen on my default profile

**Comment by Zylinder** [comment]
Policeman 0.19pre0 has introduced Redirect blocking. As I have already the Clean Links Firefox add-on handling redirects and that continuously being asked for permission redirect, I have made a custom rule for Allow - Pages - From:Any domain - To:Any domain. Worked fine until I ran into a radio link on Radionomy.com : clicking on Hotmixradio80 asks me permission to redirect to ... 

1- How can Policeman ask me permission for a redirect since I've set a rule as above mentioned?
2- Perhaps managing the Pages redirect feature through an installed set (such as i.e. HTTPS sandbox) would be pertinent, moreover because as i see it this redirect feature is not a basic, universally acclaimed Policeman feature, as it can be more embarrassing than useful providing redirects are already handled.

Thanks.

**Comment by rezad1393** [comment]
can I disable this?

**Comment by heforfree** [comment]
@rezad1393 
no you can not,for now switch back to 0.18.1

**Comment by rezad1393** [comment]
please if you want to add this feature to stable release add an option to disable it too.

ty

I was gonna remove requestpolicy addon cause I don't want to have to use two addon but more importantly I don't like the redirect blocking always enabled.
is it not possible use have separately the ability to control page requests and the redirect of whole page?

**Comment by heforfree** [comment]
i forgot to say but i think it possible with ruleset but i dont know how,sorry
there is one ruleset for samesite
https://github.com/futpib/policeman-rulesets/blob/master/general/allow_redirects_same_site.ruleset

**Comment by futpib** [comment]
@rezad1393 You can disable it by adding "allow pages from any domain to any domain" rule.

**Comment by rezad1393** [comment]
pages?
is this the new added item in new non-stable version?

**Comment by rezad1393** [comment]
ty
it worked

**Comment by rezad1393** [comment]
oh
this is buggy.
sometimes this doesn't work.
it says blocked and the element is "others".
like when using duckduckgo web search redirect it sometimes doesn't work.
this is not always occurring and refreshing the pages works.

**Comment by Halibut80** [comment]
@rezad1393 This happens because <a href="https://github.com/futpib/policeman/issues/173">https://github.com/futpib/policeman/issues/173</a>
