### ISSUE TITLE
Adding persistent rules and then killing the ff process leads to loss of the added rules

### ISSUE THREAD

**Issue by requiredregistration** [futpib/policeman#179]
the rules are not lost with normal process exit/quit

0.19pre0

**Comment by futpib** [comment]
Regardless of Firefox version changes to rules are saved periodically. Since saving involves writing all the rules, and there may be indefinitely lot of them, I don't think saving them on every change is the right way to go.

Also, rules are saved on shutdown, but Firefox does not handle `SIGTERM` properly ([336193](https://bugzilla.mozilla.org/show_bug.cgi?id=336193)).

Auto-save interval is controlled by `ruleset.autosave.checkIntervalMinutes` preference (no UI provided for that one, but you can find it on `about:config` page). The default value is 7, the hard-coded minimum is 2 (for no good reason really).

**Comment by CrisBRM** [comment]
Should implement a way to force policeman to save them manually then.
