### ISSUE TITLE
jpg "Images" detected as "Other"

### ISSUE THREAD

**Issue by Firminator** [futpib/policeman#202]
http://computerbase.de to reproduce.
![imagesother](https://cloud.githubusercontent.com/assets/12078737/7717888/c0c4c7f2-fe76-11e4-9ed9-823981c5ef82.png)

**Comment by Tanath** [comment]
Also those with .jpeg extension, and PNG as well.

**Comment by Halibut80** [comment]
https://github.com/futpib/policeman/issues/173

**Comment by chrisbura** [comment]
It looks like this is being caused by a new content type in `nsIContentPolicy`. When an image is loaded via `<img srcset="...">` it is classified as

    /**
     * Indicates a <img srcset> or <picture> request.
     */
    const nsContentPolicyType TYPE_IMAGESET = 21;

See here

http://mxr.mozilla.org/mozilla-central/source/dom/base/nsIContentPolicyBase.idl#170

Since it isn't an available content type [here](https://github.com/futpib/policeman/blob/af22168242d6f12472bbada9ee24ac3645acf40b/src/lib/ruleset/in-memory-ruleset.coffee#L211) it gets classified as `Other` [here](https://github.com/futpib/policeman/blob/049e694b546ddbd0a446bd672b93cc5437d3fe13/src/lib/ui/popup.coffee#L429).

The MDN docs haven't been updated to reflect the new content type. I ran into this problem when updating Firefox from 36 to 38 while maintaining the same Policeman version `0.18.1.1`
