### ISSUE TITLE
about "images" of policeman on Wikipedia

### ISSUE THREAD

**Issue by BEnc0de** [futpib/policeman#206]
Hi,
I don't know why that I had allowed images on "upload.wikipedia.com" when I opened "http://en.wikipedia.org/wiki/Main_Page",
http://i.imgur.com/KOAbBAB.png
but the image was blocked by policeman. Just as:
http://i.imgur.com/iJpJEVW.png
Is this bug?
I'm using PoliceMan 0.18.1.1-sgined in firefox 38.05.

**Comment by CrisBRM** [comment]
It has to do with this [bug](https://github.com/futpib/policeman/issues/202).
At any rate, policeman has essentially become abandonware, with the latest *actual* commit taking place on the 18th of February. I suggest moving to uMatrix.

**Comment by BEnc0de** [comment]
I see, so... policeman will don't update again? because I like it too, it's very good in addons.

**Comment by Gitoffthelawn** [comment]
It's very premature to call it abandonware.  It just had a commit 25 days ago.  Sometimes developers take breaks or have other things going on in their lives.

**Comment by CrisBRM** [comment]
@Gitoffthelawn the last actual update (updating the README doesn't count, merging translations don't either) was on the 18th of February, and even then, it was rather slow paced.

@BEnc0de The bugs are plentiful and the development is unbearably slow, so yeah.

**Comment by Gitoffthelawn** [comment]
@BEnc0de This extension has excellent reviews and is used by thousands of people.  My recommendation is not to let one vocal person's problems sway you into believing something.

The developer generously works on this extension without compensation at a rate that works for him/her.

**Comment by AtTheGates** [comment]
Funny how some folks think they are in the right to judge that this wonderful extension is "abandonware". The only one, who can tell it is **futpib** himself. And I think that he would let us know, if he will stop the development.

Like **Gitoffthelawn** already said, perhaps he takes just a break or has to do with other things in his live, which are more important at the moment. Or perhaps he got ill (I hope not) or just came to a point where he has to study further on this whole thing. Whatever... doesn't matter.

Damn... I hate these people who seem to have no sense of humility and appreciation. This is for free and the developers spent their whole free time. Learn to have patience!

Btw... **uMatrix** is indeed great, but in my view **Policeman** is just better. :-)

**Comment by CrisBRM** [comment]
@Gitoffthelawn I'm hardly trying to 'sway' him into believing something, other than the fact this addon isn't actively developed, and the so-called problems are real and have been documented.

@AtTheGates I'm not antagonising futpib. I merely said policeman hasn't had a *proper* commit in nearly 4 months now, whilst still having plenty of issues, some which stemming from new content types in ```nsIContentPolicy```. In short, it may not be officially classed as abandonware, he might still develop it, but for now, the development is stalled.
Regarding your claim that Policeman is 'better' than uMatrix, you are wrong. At best you can argue that you prefer Policeman's UI, because other than that, there is nothing it can do, that uMatrix can't, with the added bonus of the latter having more features, and fewer bugs. Can't really talk about performance here, as I haven't benchmarked either, but I trust gorhill's judgement as far as that goes.

**Comment by futpib** [comment]
Yeap, I'm being busy IRL, development will be stalled for at least a few weeks for sure.

@CrisBRM One killer-feature of Policeman for me is that it lets me write rules based on almost all the data `nsIContentPolicy` has to offer. I'm not experienced with uMatrix, so I might be wrong, but that looks like a thing it can do, that uMatrix can't. (But I still have no good docs or guides on it -_\\ )

Also, performance was not a primary concern when working on Policeman. It does not necessarily mean that it sucks, though I bet it's slower than uMatrix and I'm almost sure it has higher memory footprint.

**Comment by CrisBRM** [comment]
Oh, you're open to changes in the code? Gorhill is a bit more strict in that regard.

Yup, documentation was nonexistent, which resulted in a steeper learning curve. 
Regarding what you said, uMatrix supports every object type firefox's listener allows it to, and the rule syntax is nice (I think gorhill wanted to change it up a little to mirror nftables!).
It may not seem like it, but I do like your addon a lot and used it instead of noscript and requestpolicy continued, before uMatrix was released.

As it stands, the only thing policeman has over uMatrix is the ability to write rules regarding fonts, pings and websockets, because, as of today, uMatrix lists them under 'other'.

Yup, gorhill wrote uMatrix and uBlock from scratch using http switchboard and both of them borrow code from each other, and both were written with performance in mind. Policeman is pretty light though.

Keep up the good work!
