### ISSUE TITLE
Does not show blocked request on Youtube — has to allow all to make it work

### ISSUE THREAD

**Issue by magicgoose** [futpib/policeman#214]
As you can see on the screenshot below, there's a blocked request, but it's impossible to see/allow it. So I have to whitelist *all* requests from youtube to make it work, which is not so good.

![Screenshot](https://i.imgur.com/0aqLY85.png)

Also, as a workaround, maybe someone can share a working ruleset for youtube?

**Comment by Halibut80** [comment]
@magicgoose  <a href='https://github.com/futpib/policeman/issues/196#issuecomment-104672620'>https://github.com/futpib/policeman/issues/196#issuecomment-104672620</a> This works for any video that uses <a href='https://en.wikipedia.org/wiki/Media_Source_Extensions'>MSE</a>.

Also, this bug is duplicate of <a href='https://github.com/futpib/policeman/issues/196'>https://github.com/futpib/policeman/issues/196</a>

**Comment by magicgoose** [comment]
Yes, exactly. Then this issue is unnecessary, I think
